export default {
  AccountSetting: 'myAccount',
  NoticeDetail: 'notice_detail',
  ArticleDetail: 'article_detail',
  GoodsDetail: 'goods_detail',
  MyOrders: 'myOrders',
  NoticeList: 'noticeList',
  TabBar: 'tabbar',
  CustomPage: 'custom_page',
  CustomLink: 'custom_link',
  MyReceivers: 'my_receivers',
  HomePage: 'web_home',
  CardDetail: 'card_detail',
  AuthPersonal: 'auth_personal',
  AuthResult: 'auth_result',
  MyCards: 'my_cards',
  AiChat: 'aiChat',
  AiProductDetail: 'ai_product_detail',
  Share: 'share'
}
