export default {
  back: require('./back.png'),
  backAdd: require('./back_add.png'),
  arrowGray: require('./arrow_gray.png'),
  horn: require('./horn.png'),
  backWhite: require('./back_white.png'),
  close: require('./close.png'),
  search: require('./search.png'),
  copy: require('./copy.png'),
  select: require('./select.png'),
  noSelect: require('./un_select.png'),
  eye: require('./eye.png'),
  closeEye: require('./close_eye.png'),
  history: require('./history.png'),
  delete: require('./delete.png'),
  security: require('./security.png'),
  defaultAvatar: require('./default_avatar.png'),
  arrow: require('./arrow.png'),
};
