export default {
  order: require('./order.png'),
  wallet: require('./wallet.png'),
  teaTicket: require('./tea_ticket.png'),
  integral: require('./integral.png'),
  cardBag: require('./card_bag.png'),
  share: require('./share.png'),
  consignment: require('./consignment.png'),
  auth: require('./auth.png'),
  accountService: require('./account_service.png'),
  blindBox: require('./blind_box.png'),
  medal: require('./medal.png'),
  mineBg: require('./mine_bg.png'),
  personal: require('./personal.png'),
  address: require('./address.png'),
  notice: require('./notice.png'),
  security: require('./security.png'),
  about: require('./about.png'),
  delete: require('./delete.png'),
  customerService: require('./customer_service.png'),
  feedback: require('./feedback.png'),
  addAddress: require('./add_address.png'),
  authCardBG: require('./auth_card_bg.png'),
};
